# Generated by Django 4.0.1 on 2022-01-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_date', models.DateField()),
                ('hc_req', models.IntegerField()),
                ('req_raised_by', models.CharField(max_length=150)),
                ('created_by_id', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('process_type_one', models.CharField(max_length=50)),
                ('process_type_two', models.CharField(max_length=50)),
                ('process_type_three', models.CharField(max_length=50)),
                ('salary_rang_frm', models.IntegerField()),
                ('salary_rang_to', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('other_quali', models.CharField(max_length=150)),
                ('skills_set', models.TextField()),
                ('languages', models.TextField()),
                ('shift_timing', models.CharField(max_length=20)),
                ('shift_timing_frm', models.CharField(max_length=20)),
                ('shift_timing_to', models.CharField(max_length=20)),
                ('working_from', models.CharField(max_length=20)),
                ('working_to', models.CharField(max_length=20)),
                ('week_no_days', models.IntegerField()),
                ('week_from', models.CharField(max_length=20)),
                ('week_to', models.CharField(max_length=20)),
                ('requisition_type', models.CharField(max_length=50)),
                ('candidate_name', models.TextField()),
                ('closure_date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('source_empref_emp_name', models.CharField(max_length=150)),
                ('source_empref_emp_id', models.CharField(max_length=20)),
                ('source_social', models.CharField(max_length=100)),
                ('source_partners', models.CharField(max_length=100)),
                ('recruited_people', models.IntegerField()),
                ('request_status', models.CharField(default='Pending', max_length=20)),
                ('candidate_remark', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
