# Generated by Django 4.0.1 on 2022-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0002_jobrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='candidate_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='candidate_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='other_quali',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='recruited_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='request_status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='shift_timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='shift_timing_frm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='source_empref_emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='source_empref_emp_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='source_partners',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='source_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='week_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='week_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
