# Generated by Django 4.0.1 on 2022-01-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0003_alter_jobrequisition_candidate_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequisition',
        ),
    ]
