# Generated by Django 4.0.1 on 2022-01-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0006_alter_tickets_job_requisition_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequisition',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
