# Generated by Django 4.0.1 on 2022-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0008_jobrequisition_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='created_by_manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='created_by_manager_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='reason_for_replace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
