# Generated by Django 4.0.1 on 2022-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0009_jobrequisition_created_by_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='candidate_name',
            new_name='candidate_name_1',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='source_empref_emp_name',
            new_name='closed_by',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='source',
            new_name='source_1',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='source_empref_emp_id',
            new_name='source_emp_id_1',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='source_partners',
            new_name='source_partners_1',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='source_social',
            new_name='source_partners_10',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='candidate_name_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='closed_by_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_16',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_17',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_18',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_19',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_17',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_18',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_19',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_20',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_id_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_10',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_11',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_12',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_13',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_14',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_15',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_16',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_17',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_18',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_19',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_20',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_emp_name_9',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_14',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_15',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_16',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_17',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_18',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_19',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_20',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_partners_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_14',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_15',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_16',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_17',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_18',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_19',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_20',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_social_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
