# Generated by Django 4.0.1 on 2022-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0010_rename_candidate_name_jobrequisition_candidate_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='type_of_working',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
