# Generated by Django 4.0.1 on 2022-01-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0011_jobrequisition_type_of_working'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequisition',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
