# Generated by Django 3.2.9 on 2022-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0014_auto_20220202_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('manager_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='campaign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='dead_line',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_12',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_15',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_16',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_17',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_18',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_19',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_20',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_campaign_name_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_10',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_11',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_12',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_13',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_14',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_15',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_16',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_17',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_18',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_19',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_20',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_7',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_8',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_id_9',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_10',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_11',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_12',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_13',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_14',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_15',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_16',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_17',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_18',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_19',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_20',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='source_internal_emp_name_9',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
