# Generated by Django 3.2.9 on 2022-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0016_allagents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='requisition_date',
            field=models.DateTimeField(),
        ),
    ]
