# Generated by Django 3.2.9 on 2022-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0017_alter_jobrequisition_requisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
