# Generated by Django 3.2.9 on 2022-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0018_alter_jobrequisition_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='re_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='request_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
