# Generated by Django 3.2.9 on 2022-02-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0019_auto_20220204_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='re_status',
            new_name='final_status',
        ),
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='status',
            new_name='initial_status',
        ),
    ]
