# Generated by Django 3.2.9 on 2022-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0022_jobrequisition_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=30)),
                ('emp_name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('system', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
