# Generated by Django 4.0.2 on 2022-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0025_jobrequisition_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='manager_approval',
            field=models.BooleanField(default=False),
        ),
    ]
