# Generated by Django 4.0.2 on 2022-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0026_jobrequisition_manager_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='created_by_rm1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='created_by_rm1_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
