# Generated by Django 4.0.2 on 2022-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0027_jobrequisition_created_by_rm1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='reason_for_deleting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
