# Generated by Django 4.0.2 on 2022-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0028_jobrequisition_deletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='deletion',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='ticket_status',
            field=models.BooleanField(default=True),
        ),
    ]
