# Generated by Django 4.0.2 on 2022-02-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0029_remove_jobrequisition_deletion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='ticket_status',
            new_name='deletion',
        ),
    ]
