# Generated by Django 4.0.2 on 2022-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_requisition_app', '0030_rename_ticket_status_jobrequisition_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='ticket_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='deletion',
            field=models.BooleanField(default=False),
        ),
    ]
